from datetime import timedelta
from decimal import Decimal

SAMPLE_SKILLS = [
    "Welding",
    "Machine Operation",
    "PLC Programming",
    "CNC Machining",
    "Inventory Tracking",
    "Electrical Maintenance",
    "Pneumatic Systems",
    "3D Modeling",
    "Tool Calibration",
    "Safety Auditing",
    "Packaging",
    "System Troubleshooting",
    "Blueprint Reading",
    "Hydraulic Systems",
    "Preventive Maintenance",
    "Laser Cutting",
    "CAD Drafting",
    "Robotic Arm Operation",
    "Industrial Automation",
    "Material Handling",
    "Quality Control Inspection",
    "Lean Manufacturing",
    "Six Sigma Methodologies",
    "Forklift Operation",
    "Soldering",
    "HVAC Maintenance",
    "Assembly Line Supervision",
    "Root Cause Analysis",
    "Technical Documentation",
    "OSHA Compliance",
]

SKILL_CATEGORIES = {
    "Welding": "MECHANICAL",
    "Machine Operation": "MECHANICAL",
    "PLC Programming": "ELECTRICAL",
    "CNC Machining": "MECHANICAL",
    "Inventory Tracking": "LOGISTICS",
    "Electrical Maintenance": "ELECTRICAL",
    "Pneumatic Systems": "MECHANICAL",
    "3D Modeling": "DESIGN",
    "Tool Calibration": "TECHNICAL",
    "Safety Auditing": "SAFETY",
    "Packaging": "OPERATIONS",
    "System Troubleshooting": "TECHNICAL",
    "Blueprint Reading": "DESIGN",
    "Hydraulic Systems": "MECHANICAL",
    "Preventive Maintenance": "MAINTENANCE",
    "Laser Cutting": "MECHANICAL",
    "CAD Drafting": "DESIGN",
    "Robotic Arm Operation": "MECHANICAL",
    "Industrial Automation": "ELECTRICAL",
    "Material Handling": "LOGISTICS",
    "Quality Control Inspection": "QUALITY_CONTROL",
    "Lean Manufacturing": "MANAGEMENT",
    "Six Sigma Methodologies": "MANAGEMENT",
    "Forklift Operation": "LOGISTICS",
    "Soldering": "ELECTRICAL",
    "HVAC Maintenance": "MAINTENANCE",
    "Assembly Line Supervision": "MANAGEMENT",
    "Root Cause Analysis": "TECHNICAL",
    "Technical Documentation": "ADMINISTRATION",
    "OSHA Compliance": "SAFETY",
}

SAMPLE_DEPARTMENTS = [
    "Production Department",
    "Quality Control Department",
    "Inventory & Warehouse Department",
    "Procurement Department",
    "Maintenance Department",
    "Human Resources Department",
    "Finance & Accounting Department",
    "Research & Development Department",
    "Sales & Marketing Department",
    "IT & Systems Department",
    "Health, Safety & Environment Department",
]

SAMPLE_WORKSHOPS = {
    "Production Department": [
        "Assembly Workshop",
        "Fabrication Workshop",
        "Machining Workshop",
        "Welding Workshop",
        "Molding and Casting Workshop",
        "Painting and Finishing Workshop",
    ],
    "Quality Control Department": [
        "Testing Workshop",
        "Inspection Workshop",
        "Calibration Workshop",
        "Metrology Lab",
    ],
    "Inventory & Warehouse Department": [
        "Packaging Workshop",
        "Sorting and Distribution Workshop",
        "Material Handling Workshop",
    ],
    "Procurement Department": [
        "Vendor Evaluation Workshop",
        "Material Inspection Workshop",
        "Receiving Workshop",
    ],
    "Maintenance Department": [
        "Equipment Repair Workshop",
        "Preventive Maintenance Workshop",
        "Tool Room Workshop",
        "Electrical Maintenance Workshop",
        "Mechanical Maintenance Workshop",
    ],
    "Human Resources Department": [
        "Training Workshop",
        "Onboarding Workshop",
        "Skills Development Center",
    ],
    "Finance & Accounting Department": [
        "Cost Analysis Workshop",
        "Auditing Workshop",
        "Budget Planning Workshop",
    ],
    "Research & Development Department": [
        "Prototyping Workshop",
        "Materials Testing Workshop",
        "Design Workshop",
        "Innovation Lab",
    ],
    "Sales & Marketing Department": [
        "Product Demonstration Workshop",
        "Sample Development Workshop",
        "Customer Experience Center",
    ],
    "IT & Systems Department": [
        "Hardware Repair Workshop",
        "Network Operations Center",
        "Software Development Workshop",
    ],
    "Health, Safety & Environment Department": [
        "Safety Training Workshop",
        "Emergency Response Workshop",
        "Environmental Testing Lab",
        "Waste Management Workshop",
    ],
}

WORKSHOP_DESCRIPTIONS = {
    "Assembly Workshop": "Final assembly of products with multiple components.",
    "Fabrication Workshop": "Creation of product components from raw materials.",
    "Machining Workshop": "Precision cutting and shaping of materials.",
    "Welding Workshop": "Joining of materials through various welding processes.",
    "Molding and Casting Workshop": "Creating parts through molding and casting techniques.",
    "Painting and Finishing Workshop": "Application of final coatings and finishes to products.",
    "Testing Workshop": "Conducting various tests to verify product quality.",
    "Inspection Workshop": "Visual and dimensional inspection of products.",
    "Calibration Workshop": "Calibration of measuring instruments and tools.",
    "Metrology Lab": "Precision measurement and analysis of product dimensions.",
    "Packaging Workshop": "Product packaging for shipment and distribution.",
    "Sorting and Distribution Workshop": "Organization and distribution of materials and products.",
    "Material Handling Workshop": "Management of material movement within the facility.",
    "Vendor Evaluation Workshop": "Assessment of supplier capabilities and products.",
    "Material Inspection Workshop": "Inspection of incoming materials from suppliers.",
    "Receiving Workshop": "Receipt and verification of incoming shipments.",
    "Equipment Repair Workshop": "Repair of factory machinery and equipment.",
    "Preventive Maintenance Workshop": "Regular maintenance to prevent equipment failure.",
    "Tool Room Workshop": "Management and maintenance of production tools.",
    "Electrical Maintenance Workshop": "Maintenance of electrical systems and equipment.",
    "Mechanical Maintenance Workshop": "Maintenance of mechanical systems and equipment.",
    "Training Workshop": "Employee training for various job functions.",
    "Onboarding Workshop": "Introduction and orientation for new employees.",
    "Skills Development Center": "Advanced training to enhance employee skills.",
    "Cost Analysis Workshop": "Analysis of production costs and efficiency.",
    "Auditing Workshop": "Internal auditing of financial and operational processes.",
    "Budget Planning Workshop": "Planning and allocation of departmental budgets.",
    "Prototyping Workshop": "Development of product prototypes for testing.",
    "Materials Testing Workshop": "Testing of materials for product development.",
    "Design Workshop": "Product design and engineering.",
    "Innovation Lab": "Research and development of new product concepts.",
    "Product Demonstration Workshop": "Showcasing products to potential customers.",
    "Sample Development Workshop": "Creation of product samples for sales team.",
    "Customer Experience Center": "Facility for customer interaction and product demos.",
    "Hardware Repair Workshop": "Repair and maintenance of computer hardware.",
    "Network Operations Center": "Management and monitoring of network infrastructure.",
    "Software Development Workshop": "Creation and testing of software applications.",
    "Safety Training Workshop": "Employee training on safety protocols.",
    "Emergency Response Workshop": "Training and equipment for emergency situations.",
    "Environmental Testing Lab": "Testing environmental impact of operations.",
    "Waste Management Workshop": "Management and disposal of industrial waste.",
}

SAMPLE_MACHINES = {
    # Production Department
    "Assembly Workshop": [
        {"name": "Automated Assembly Line", "model_number": "AAL-2000"},
        {"name": "Robotic Assembler", "model_number": "RA-750"},
        {"name": "Conveyor System", "model_number": "CS-500"},
        {"name": "Industrial Adhesive Dispenser", "model_number": "IAD-100"},
    ],
    "Fabrication Workshop": [
        {"name": "CNC Fabricator", "model_number": "CF-3500"},
        {"name": "Sheet Metal Cutter", "model_number": "SMC-2000"},
        {"name": "Plasma Cutter", "model_number": "PC-1500"},
        {"name": "CNC Bending Machine", "model_number": "BM-4000"},
    ],
    "Machining Workshop": [
        {"name": "CNC Mill", "model_number": "CNM-5000"},
        {"name": "CNC Lathe", "model_number": "CNL-3000"},
        {"name": "Surface Grinder", "model_number": "SG-1200"},
        {"name": "Industrial Drill Press", "model_number": "DP-800"},
        {"name": "EDM Machine", "model_number": "EDM-400"},
    ],
    "Welding Workshop": [
        {"name": "MIG Welder", "model_number": "MIG-350"},
        {"name": "TIG Welder", "model_number": "TIG-250"},
        {"name": "Spot Welding Machine", "model_number": "SWM-100"},
        {"name": "Robotic Welding Arm", "model_number": "RWA-2000"},
        {"name": "Laser Welder", "model_number": "LW-500"},
    ],
    "Molding and Casting Workshop": [
        {"name": "Injection Molding Machine", "model_number": "IMM-3000"},
        {"name": "Die-Casting Machine", "model_number": "DCM-2500"},
        {"name": "Vacuum Forming Equipment", "model_number": "VFE-1000"},
        {"name": "Rotational Molding Machine", "model_number": "RMM-1500"},
    ],
    "Painting and Finishing Workshop": [
        {"name": "Paint Booth", "model_number": "PB-2000"},
        {"name": "Powder Coating Equipment", "model_number": "PCE-1500"},
        {"name": "Industrial Sander", "model_number": "IS-500"},
        {"name": "Polishing Machine", "model_number": "PM-300"},
    ],
    # Quality Control Department
    "Testing Workshop": [
        {"name": "Tensile Testing Machine", "model_number": "TTM-1000"},
        {"name": "Impact Tester", "model_number": "IT-500"},
        {"name": "Hardness Tester", "model_number": "HT-300"},
        {"name": "Fatigue Testing Machine", "model_number": "FTM-2000"},
    ],
    "Inspection Workshop": [
        {"name": "Coordinate Measuring Machine", "model_number": "CMM-3000"},
        {"name": "Vision Inspection System", "model_number": "VIS-2000"},
        {"name": "X-Ray Inspection System", "model_number": "XRI-5000"},
    ],
    "Calibration Workshop": [
        {"name": "Gauge Calibrator", "model_number": "GC-500"},
        {"name": "Electronic Calibration Device", "model_number": "ECD-1000"},
        {"name": "Temperature Calibrator", "model_number": "TC-300"},
    ],
    "Metrology Lab": [
        {"name": "Precision Scale", "model_number": "PS-100"},
        {"name": "3D Scanner", "model_number": "3DS-2000"},
        {"name": "Surface Roughness Tester", "model_number": "SRT-500"},
        {"name": "Optical Comparator", "model_number": "OC-1000"},
    ],
    # Inventory & Warehouse Department
    "Packaging Workshop": [
        {"name": "Automated Packaging Machine", "model_number": "APM-2000"},
        {"name": "Shrink Wrap Machine", "model_number": "SWM-1000"},
        {"name": "Box Erector", "model_number": "BE-500"},
        {"name": "Labeling Machine", "model_number": "LM-300"},
    ],
    "Sorting and Distribution Workshop": [
        {"name": "Conveyor Sorter", "model_number": "CS-2000"},
        {"name": "Automated Guided Vehicle", "model_number": "AGV-1000"},
        {"name": "Sorting Robot", "model_number": "SR-3000"},
    ],
    "Material Handling Workshop": [
        {"name": "Electric Forklift", "model_number": "EF-2000"},
        {"name": "Hydraulic Pallet Jack", "model_number": "HPJ-500"},
        {"name": "Overhead Crane", "model_number": "OC-5000"},
        {"name": "Automated Storage System", "model_number": "ASS-10000"},
    ],
    # Procurement Department
    "Vendor Evaluation Workshop": [
        {"name": "Material Testing Station", "model_number": "MTS-1000"},
        {"name": "Quality Assessment System", "model_number": "QAS-500"},
    ],
    "Material Inspection Workshop": [
        {"name": "Spectrophotometer", "model_number": "SP-2000"},
        {"name": "Material Analyzer", "model_number": "MA-1500"},
        {"name": "Digital Microscope", "model_number": "DM-500"},
    ],
    "Receiving Workshop": [
        {"name": "Automated Weighing System", "model_number": "AWS-2000"},
        {"name": "Barcode Scanner System", "model_number": "BSS-500"},
        {"name": "Package X-Ray", "model_number": "PX-1000"},
    ],
    # Maintenance Department
    "Equipment Repair Workshop": [
        {"name": "Hydraulic Press", "model_number": "HP-5000"},
        {"name": "CNC Machine Repair Station", "model_number": "CMRS-3000"},
        {"name": "Electrical Test Bench", "model_number": "ETB-1000"},
    ],
    "Preventive Maintenance Workshop": [
        {"name": "Preventive Maintenance Station", "model_number": "PMS-2000"},
        {"name": "Lubrication System", "model_number": "LS-500"},
        {"name": "Diagnostic Equipment", "model_number": "DE-1000"},
    ],
    "Tool Room Workshop": [
        {"name": "Tool Grinder", "model_number": "TG-500"},
        {"name": "Sharpening Machine", "model_number": "SM-300"},
        {"name": "Heat Treatment Furnace", "model_number": "HTF-2000"},
    ],
    "Electrical Maintenance Workshop": [
        {"name": "Oscilloscope", "model_number": "OSC-1000"},
        {"name": "Power Analyzer", "model_number": "PA-500"},
        {"name": "Cable Tester", "model_number": "CT-300"},
        {"name": "Circuit Board Repair Station", "model_number": "CBRS-2000"},
    ],
    "Mechanical Maintenance Workshop": [
        {"name": "Lathe Machine", "model_number": "LM-1000"},
        {"name": "Hydraulic Press", "model_number": "HP-2000"},
        {"name": "Balancing Machine", "model_number": "BM-1500"},
        {"name": "Bearing Puller Set", "model_number": "BPS-500"},
    ],
    # Research & Development Department
    "Prototyping Workshop": [
        {"name": "Industrial 3D Printer", "model_number": "3DP-5000"},
        {"name": "Laser Cutter", "model_number": "LC-2000"},
        {"name": "CNC Prototyping Machine", "model_number": "CPM-3000"},
        {"name": "Rapid Prototyping System", "model_number": "RPS-4000"},
    ],
    "Materials Testing Workshop": [
        {"name": "Universal Testing Machine", "model_number": "UTM-2000"},
        {"name": "Digital Microscope", "model_number": "DM-1000"},
        {"name": "Spectrometer", "model_number": "SM-3000"},
        {"name": "Thermal Analysis Equipment", "model_number": "TAE-2000"},
    ],
    "Design Workshop": [
        {"name": "3D Scanner", "model_number": "3DS-2000"},
        {"name": "VR Design System", "model_number": "VRDS-5000"},
        {"name": "CAD Workstation", "model_number": "CW-3000"},
    ],
    "Innovation Lab": [
        {"name": "Material Fabrication System", "model_number": "MFS-2000"},
        {"name": "Chemical Analysis Equipment", "model_number": "CAE-3000"},
        {"name": "Experimental Testing Rig", "model_number": "ETR-1000"},
    ],
    # Sales & Marketing Department
    "Product Demonstration Workshop": [
        {"name": "Interactive Display System", "model_number": "IDS-2000"},
        {"name": "Product Demo Robot", "model_number": "PDR-1000"},
        {"name": "AR/VR Experience Station", "model_number": "ARVR-3000"},
    ],
    "Sample Development Workshop": [
        {"name": "Sample Fabrication Machine", "model_number": "SFM-1000"},
        {"name": "Custom Packaging Printer", "model_number": "CPP-500"},
        {"name": "Material Sample Cutter", "model_number": "MSC-300"},
    ],
    "Customer Experience Center": [
        {"name": "Interactive Touch Display", "model_number": "ITD-2000"},
        {"name": "Product Testing Station", "model_number": "PTS-1000"},
        {"name": "Digital Product Catalog", "model_number": "DPC-500"},
    ],
    # IT & Systems Department
    "Hardware Repair Workshop": [
        {"name": "Soldering Station", "model_number": "SS-500"},
        {"name": "Circuit Tester", "model_number": "CT-300"},
        {"name": "Component Analyzer", "model_number": "CA-1000"},
        {"name": "PCB Rework Station", "model_number": "PRS-2000"},
    ],
    "Network Operations Center": [
        {"name": "Network Testing Equipment", "model_number": "NTE-1000"},
        {"name": "Cable Certification Tool", "model_number": "CCT-500"},
        {"name": "Server Rack System", "model_number": "SRS-5000"},
    ],
    "Software Development Workshop": [
        {"name": "High-Performance Workstation", "model_number": "HPW-3000"},
        {"name": "Software Testing Rig", "model_number": "STR-2000"},
        {"name": "Development Server Cluster", "model_number": "DSC-5000"},
    ],
    # Health, Safety & Environment Department
    "Safety Training Workshop": [
        {"name": "Safety Simulation System", "model_number": "SSS-2000"},
        {"name": "VR Safety Training Station", "model_number": "VRSTS-3000"},
        {"name": "Emergency Response Simulator", "model_number": "ERS-1000"},
    ],
    "Emergency Response Workshop": [
        {"name": "Fire Training System", "model_number": "FTS-2000"},
        {"name": "Rescue Training Equipment", "model_number": "RTE-1000"},
        {"name": "First Aid Training Station", "model_number": "FATS-500"},
    ],
    "Environmental Testing Lab": [
        {"name": "Air Quality Monitor", "model_number": "AQM-1000"},
        {"name": "Water Testing Equipment", "model_number": "WTE-2000"},
        {"name": "Noise Level Analyzer", "model_number": "NLA-500"},
        {"name": "Emissions Testing System", "model_number": "ETS-3000"},
    ],
    "Waste Management Workshop": [
        {"name": "Waste Compactor", "model_number": "WC-2000"},
        {"name": "Industrial Shredder", "model_number": "IS-3000"},
        {"name": "Material Separator", "model_number": "MS-1000"},
        {"name": "Baler Machine", "model_number": "BM-1500"},
    ],
    # Human Resources Department
    "Training Workshop": [
        {"name": "Interactive Training System", "model_number": "ITS-1000"},
        {"name": "Virtual Training Station", "model_number": "VTS-2000"},
        {"name": "Digital Learning Pod", "model_number": "DLP-500"},
    ],
    "Onboarding Workshop": [
        {"name": "Badge Creation System", "model_number": "BCS-500"},
        {"name": "Digital Onboarding Station", "model_number": "DOS-1000"},
        {"name": "Employee Registration System", "model_number": "ERS-300"},
    ],
    "Skills Development Center": [
        {"name": "Skill Assessment Station", "model_number": "SAS-1000"},
        {"name": "Technical Training Simulator", "model_number": "TTS-2000"},
        {"name": "Leadership Development System", "model_number": "LDS-1500"},
    ],
    # Finance & Accounting Department
    "Cost Analysis Workshop": [
        {"name": "Cost Modeling System", "model_number": "CMS-2000"},
        {"name": "Financial Analysis Workstation", "model_number": "FAW-1000"},
        {"name": "Data Processing Server", "model_number": "DPS-3000"},
    ],
    "Auditing Workshop": [
        {"name": "Document Scanner Array", "model_number": "DSA-1000"},
        {"name": "Secure Data Processing Unit", "model_number": "SDPU-2000"},
        {"name": "Financial Records Server", "model_number": "FRS-5000"},
    ],
    "Budget Planning Workshop": [
        {"name": "Budget Modeling System", "model_number": "BMS-2000"},
        {"name": "Financial Projection Station", "model_number": "FPS-1000"},
        {"name": "Data Visualization Server", "model_number": "DVS-3000"},
    ],
}

MATERIALS = [
    {
        "name": "Steel Sheets",
        "description": "High-quality cold-rolled steel sheets for manufacturing",
        "unit_of_measurement": "kg",
        "quantity": Decimal(950.00),
        "reorder_level": Decimal(250.00),
    },
    {
        "name": "Aluminum Extrusions",
        "description": "Durable aluminum extrusions for structural components and frameworks",
        "unit_of_measurement": "m",
        "quantity": Decimal(620.00),
        "reorder_level": Decimal(150.00),
    },
    {
        "name": "Plastic Granules",
        "description": "Virgin plastic granules used in injection molding machines",
        "unit_of_measurement": "kg",
        "quantity": Decimal(780.00),
        "reorder_level": Decimal(200.00),
    },
    {
        "name": "Copper Wire",
        "description": "High-conductivity copper wire for use in electrical systems",
        "unit_of_measurement": "m",
        "quantity": Decimal(1100.00),
        "reorder_level": Decimal(300.00),
    },
    {
        "name": "Silicon Wafers",
        "description": "High-purity, 300mm silicon wafers for chip fabrication",
        "unit_of_measurement": "pcs",
        "quantity": Decimal(4500.00),
        "reorder_level": Decimal(1000.00),
    },
    {
        "name": "Industrial Lubricant",
        "description": "Multi-purpose lubricant oil for heavy machinery",
        "unit_of_measurement": "liters",
        "quantity": Decimal(320.00),
        "reorder_level": Decimal(100.00),
    },
    {
        "name": "Carbon Fiber Sheets",
        "description": "Lightweight, high-strength carbon fiber sheets for advanced components",
        "unit_of_measurement": "sqm",
        "quantity": Decimal(150.00),
        "reorder_level": Decimal(50.00),
    },
    {
        "name": "Epoxy Resin",
        "description": "Industrial-grade epoxy resin for composites and adhesives",
        "unit_of_measurement": "liters",
        "quantity": Decimal(400.00),
        "reorder_level": Decimal(80.00),
    },
    {
        "name": "Brass Rods",
        "description": "Machinable brass rods for fittings and connectors",
        "unit_of_measurement": "m",
        "quantity": Decimal(300.00),
        "reorder_level": Decimal(75.00),
    },
    {
        "name": "Stainless Steel Bolts",
        "description": "Corrosion-resistant stainless steel bolts for structural assembly",
        "unit_of_measurement": "pcs",
        "quantity": Decimal(2000.00),
        "reorder_level": Decimal(500.00),
    },
]

SAMPLE_PRODUCTION_LINES = [
    "Line A",
    "Line B",
    "Line C",
    "Line D",
    "Line E",
    "Line F",
    "Line G",
    "Line H",
    "Line I",
    "Line J",
]

SAMPLE_PRODUCTION_LINE_CAPACITIES = [
    Decimal(100.00),
    Decimal(150.00),
    Decimal(200.00),
    Decimal(250.00),
    Decimal(300.00),
]

SAMPLE_Manufacturing_Process = [
    {
        "name": "CNC Machining",
        "description": "Computer numerical control machining process for cutting and shaping metal parts with high precision.",
        "standard_time": timedelta(hours=2, minutes=30),
        "quality_parameters": {
            "tolerance": "±0.005 mm",
            "surface_finish": "Ra 0.8μm",
            "hardness_check": True,
            "inspection_points": ["dimensions", "surface quality", "thread quality"],
        },
    },
    {
        "name": "Injection Molding",
        "description": "Process for manufacturing parts by injecting molten material into a mold cavity.",
        "standard_time": timedelta(minutes=45),
        "quality_parameters": {
            "temperature": "220-250°C",
            "pressure": "80-120 MPa",
            "cooling_time": "20-30s",
            "inspection_points": [
                "flash",
                "sink marks",
                "weld lines",
                "dimensional accuracy",
            ],
        },
    },
    {
        "name": "Welding Assembly",
        "description": "Process of joining metal components using MIG/TIG welding techniques.",
        "standard_time": timedelta(hours=1, minutes=15),
        "quality_parameters": {
            "weld_strength": "450 MPa",
            "penetration": "3-5mm",
            "visual_inspection": ["porosity", "undercut", "spatter"],
            "testing_methods": ["visual", "dye penetrant", "ultrasonic"],
        },
    },
    {
        "name": "Surface Treatment",
        "description": "Application of protective or decorative coatings to product surfaces.",
        "standard_time": timedelta(hours=3, minutes=0),
        "quality_parameters": {
            "coating_thickness": "50-75 microns",
            "adhesion_test": "ASTM D3359",
            "corrosion_resistance": "240 hours salt spray",
            "appearance": ["color matching", "orange peel", "runs", "sags"],
        },
    },
    {
        "name": "Heat Treatment",
        "description": "Controlled heating and cooling process to alter the physical properties of materials.",
        "standard_time": timedelta(hours=4, minutes=30),
        "quality_parameters": {
            "temperature_profile": {
                "ramp_up": "150°C/h",
                "hold": "950°C for 2h",
                "cooling": "controlled at 50°C/h",
            },
            "hardness_target": "58-62 HRC",
            "microstructure": "fine martensitic",
            "testing_methods": ["hardness testing", "microstructure analysis"],
        },
    },
    {
        "name": "PCB Assembly",
        "description": "Mounting of electronic components onto printed circuit boards.",
        "standard_time": timedelta(minutes=35),
        "quality_parameters": {
            "soldering_temperature": "245-255°C",
            "component_placement": "±0.1mm accuracy",
            "inspection_methods": ["AOI", "X-ray", "functional testing"],
            "defect_types": [
                "cold solder",
                "bridging",
                "missing components",
                "misalignment",
            ],
        },
    },
    {
        "name": "Powder Coating",
        "description": "Dry finishing process that applies a free-flowing powder to a surface and cures with heat.",
        "standard_time": timedelta(hours=1, minutes=45),
        "quality_parameters": {
            "powder_thickness": "60-80 microns",
            "cure_temperature": "180-200°C",
            "cure_time": "10-15 minutes",
            "quality_checks": [
                "adhesion",
                "impact resistance",
                "flexibility",
                "color consistency",
            ],
        },
    },
    {
        "name": "Laser Cutting",
        "description": "Precision cutting of materials using a high-powered laser beam.",
        "standard_time": timedelta(minutes=20),
        "quality_parameters": {
            "kerf_width": "0.15mm",
            "edge_quality": "smooth, dross-free",
            "dimensional_accuracy": "±0.1mm",
            "heat_affected_zone": "minimal",
        },
    },
    {
        "name": "Final Assembly",
        "description": "Putting together all components to create the final product.",
        "standard_time": timedelta(hours=1, minutes=0),
        "quality_parameters": {
            "torque_specifications": {"M6": "8-10 Nm", "M8": "20-25 Nm"},
            "gap_tolerances": "±0.5mm",
            "functional_tests": ["operation", "noise level", "movement"],
            "cosmetic_requirements": "No visible defects from 1m distance",
        },
    },
    {
        "name": "Quality Inspection",
        "description": "Final verification of product quality before packaging.",
        "standard_time": timedelta(minutes=15),
        "quality_parameters": {
            "sampling_rate": "100% for critical features, AQL 2.5 for others",
            "measurement_tools": ["calipers", "CMM", "vision systems"],
            "documentation": ["inspection report", "traceability data"],
            "acceptance_criteria": "Zero defects on critical characteristics",
        },
    },
]

SAMPLE_PRODUCTS = [
    {
        "name": "Industrial Water Pump",
        "code": "IWP2000",
        "unit_of_measurement": "unit",
        "specifications": {
            "motor_power": "2.2 kW",
            "max_flow_rate": "500 L/min",
            "max_head": "25 meters",
            "inlet_diameter": "50 mm",
            "outlet_diameter": "40 mm",
            "material": "Stainless Steel 304",
            "weight": "18 kg",
            "dimensions": "420 x 240 x 320 mm",
        },
    },
    {
        "name": "Control Panel Housing",
        "code": "CPH450",
        "unit_of_measurement": "unit",
        "specifications": {
            "dimensions": "600 x 400 x 200 mm",
            "material": "Carbon Steel",
            "thickness": "1.5 mm",
            "protection_class": "IP54",
            "mounting": "Wall mounted",
            "finish": "Powder coated RAL 7035",
            "weight": "12 kg",
        },
    },
    {
        "name": "Hydraulic Cylinder",
        "code": "HC350",
        "unit_of_measurement": "unit",
        "specifications": {
            "bore_diameter": "63 mm",
            "rod_diameter": "36 mm",
            "stroke": "500 mm",
            "operating_pressure": "210 bar",
            "material": "Honed ST52 steel tube",
            "rod_material": "Hard chrome plated C45",
            "max_force": "65.6 kN",
            "mounting_type": "Clevis",
        },
    },
    {
        "name": "Circuit Control Board",
        "code": "CCB120",
        "unit_of_measurement": "piece",
        "specifications": {
            "dimensions": "120 x 80 mm",
            "layers": "4",
            "material": "FR-4",
            "thickness": "1.6 mm",
            "copper_weight": "1 oz",
            "surface_finish": "HASL lead-free",
            "components": ["resistors", "capacitors", "IC chips", "connectors"],
        },
    },
    {
        "name": "Gear Assembly",
        "code": "GA550",
        "unit_of_measurement": "assembly",
        "specifications": {
            "gear_ratio": "4:1",
            "tooth_count": {"pinion": 15, "gear": 60},
            "material": "Case hardened steel",
            "module": "2.0",
            "pressure_angle": "20°",
            "max_torque": "150 Nm",
            "bearing_type": "Deep groove ball bearing",
        },
    },
    {
        "name": "Custom Enclosure",
        "code": "CE200",
        "unit_of_measurement": "unit",
        "specifications": {
            "dimensions": "300 x 200 x 150 mm",
            "material": "ABS plastic",
            "wall_thickness": "3 mm",
            "color": "Black",
            "flame_retardant": "UL94V-0",
            "features": ["cable glands", "mounting bosses", "transparent window"],
        },
    },
    {
        "name": "Pneumatic Actuator",
        "code": "PA100",
        "unit_of_measurement": "unit",
        "specifications": {
            "type": "Double acting",
            "bore": "50 mm",
            "stroke": "100 mm",
            "operating_pressure": "1-10 bar",
            "material": "Anodized aluminum",
            "seal_material": "NBR",
            "mounting": "ISO 15552 standard",
            "operating_temp": "-10°C to +70°C",
        },
    },
    {
        "name": "Motor Shaft",
        "code": "MS120",
        "unit_of_measurement": "piece",
        "specifications": {
            "diameter": "25 mm",
            "length": "150 mm",
            "material": "Carbon steel C45",
            "hardness": "55 HRC",
            "surface_finish": "Ground Ra 0.4",
            "keyway": "8 x 4 mm",
            "tolerance": "h7",
        },
    },
    {
        "name": "Vibration Dampener",
        "code": "VD75",
        "unit_of_measurement": "piece",
        "specifications": {
            "material": "Natural rubber",
            "hardness": "45 Shore A",
            "dimensions": "75 x 50 x 40 mm",
            "max_load": "80 kg",
            "operating_temp": "-30°C to +70°C",
            "resonant_frequency": "8 Hz",
            "mounting_holes": "2 x M8",
        },
    },
    {
        "name": "Safety Guard",
        "code": "SG500",
        "unit_of_measurement": "unit",
        "specifications": {
            "dimensions": "800 x 500 mm",
            "material": "Perforated steel sheet",
            "thickness": "1.5 mm",
            "mesh_size": "8 x 8 mm",
            "frame": "25 x 25 mm square tube",
            "finish": "Powder coated yellow RAL 1003",
            "standards": ["ISO 14120", "ISO 13857"],
        },
    },
    {
        "name": "Cooling System",
        "code": "CS300",
        "unit_of_measurement": "unit",
        "specifications": {
            "cooling_capacity": "3 kW",
            "fans": "2 x 120 mm",
            "airflow": "220 CFM",
            "power_consumption": "40W",
            "noise_level": "45 dB(A)",
            "dimensions": "300 x 200 x 150 mm",
            "weight": "4.5 kg",
        },
    },
    {
        "name": "Legacy Pressure Gauge",
        "code": "LPG100",
        "unit_of_measurement": "piece",
        "specifications": {
            "diameter": "100 mm",
            "range": "0-10 bar",
            "accuracy": "±1.6%",
            "connection": '1/2" BSP',
            "case_material": "Stainless steel",
            "window_material": "Safety glass",
            "filling": "Glycerin",
        },
    },
]

project_names = [
    "Manufacturing Line Optimization",
    "Quality Control System Upgrade",
    "Inventory Management Implementation",
    "Production Scheduling Automation",
    "Equipment Maintenance Program",
    "Safety Protocol Enhancement",
    "Cost Reduction Initiative",
    "Product Development Phase 1",
    "Supply Chain Integration",
    "Lean Manufacturing Implementation",
]

task_templates = [
    "Requirements Analysis",
    "System Design",
    "Implementation",
    "Testing & Validation",
    "Deployment & Documentation",
]
