# Generated by Django 5.2.7 on 2025-12-25 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_material_inventory_m_name_1014de_idx'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity consumed')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='consumed at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_material_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='consumed by')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_consumptions', to='inventory.material', verbose_name='material')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='project.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Task Material Consumption',
                'verbose_name_plural': 'Task Material Consumptions',
                'ordering': ['-consumed_at'],
                'indexes': [models.Index(fields=['task', 'material'], name='project_tas_task_id_37919f_idx'), models.Index(fields=['consumed_at'], name='project_tas_consume_3eab98_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='task_consumption_quantity_positive')],
            },
        ),
    ]
