# Generated by Django 5.2.7 on 2026-02-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_taskmaterialconsumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskMaterialConsumption',
        ),
    ]
