apiVersion: v1
kind: ConfigMap
metadata:
  name: fms-prod-config
  namespace: fms-prod
data:
  DATABASE_ENGINE: "postgresql_psycopg2"
  DATABASE_HOST: "fms-prod-database"
  DATABASE_PORT: "5432"
  REDIS_HOST: "fms-prod-redis"
  REDIS_PORT: "6379"
  DEBUG: "False"
  API_PORT: "8000"
  CORS_ORIGINS: "http://fms.prod.com,https://fms.prod.com,http://localhost,http://host.docker.internal,http://host.docker.internal:80"
  ALLOWED_HOSTS: "fms.prod.com,fms-prod-backend,fms-prod-backend.fms-prod,fms-prod-backend.fms-prod.svc.cluster.local,localhost,127.0.0.1"
  GOOGLE_CALLBACK_URL: "http://fms.prod.com,http://localhost"
