# Generated by Django 5.2.7 on 2025-10-04 13:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50, null=True, verbose_name='unit of measurement')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='quantity')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='reorder level')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_m_name_1014de_idx'), models.Index(fields=['quantity'], name='inventory_m_quantit_118ae7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='material_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='material_reorder_level_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='phone no')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_s_name_d435cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='order date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('CANCELLED', 'Cancelled'), ('RECEIVED', 'Received Complete')], db_index=True, default='DRAFT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.supplier')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total price')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_materials', to='inventory.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_materials', to='inventory.order')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='inventory_o_order_i_ab6e08_idx'), models.Index(fields=['material'], name='inventory_o_materia_1b3d18_idx')],
                'unique_together': {('order', 'material')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['supplier', 'status'], name='inventory_o_supplie_84b774_idx'),
        ),
    ]
