# Generated by Django 5.2.7 on 2025-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_order_invoice'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ordermaterial',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_material_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='ordermaterial',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_material_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='ordermaterial',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='order_material_total_price_non_negative'),
        ),
    ]
