# Generated by Django 5.2.7 on 2025-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_ordermaterial_order_material_quantity_positive_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='material',
            name='inventory_m_name_1014de_idx',
        ),
    ]
