# Generated by Django 5.2.7 on 2026-02-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_material_inventory_m_name_1014de_idx'),
        ('production', '0004_delete_productionmaterialconsumption'),
        ('project', '0003_delete_taskmaterialconsumption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_type', models.CharField(choices=[('TASK', 'Task'), ('PRODUCTION', 'Production Schedule')], max_length=20, verbose_name='consumption type')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity consumed')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='consumed at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='consumed by')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.material', verbose_name='material')),
                ('production_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionschedule', verbose_name='production schedule')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='project.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'Material Consumption',
                'verbose_name_plural': 'Material Consumptions',
                'ordering': ['-consumed_at'],
                'indexes': [models.Index(fields=['material', 'consumption_type'], name='inventory_m_materia_4f26b6_idx'), models.Index(fields=['task', 'material'], name='inventory_m_task_id_c7c47f_idx'), models.Index(fields=['production_schedule', 'material'], name='inventory_m_product_6ab386_idx'), models.Index(fields=['consumed_at'], name='inventory_m_consume_1a600e_idx'), models.Index(fields=['consumed_by'], name='inventory_m_consume_71d311_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='consumption_quantity_positive')],
            },
        ),
    ]
