# Generated by Django 5.2.7 on 2025-10-05 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_alter_productionline_description_and_more'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_allocated', models.DecimalField(decimal_places=2, default=4.0, max_digits=10, verbose_name='hours allocated')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_allocations', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_allocations', to='production.productionline', verbose_name='production line')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_allocations', to='project.project', verbose_name='project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_allocations', to='project.task', verbose_name='task')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'date'], name='labor_labor_employe_95204b_idx'), models.Index(fields=['project', 'date'], name='labor_labor_project_98f0ba_idx'), models.Index(fields=['task', 'date'], name='labor_labor_task_id_fe6110_idx'), models.Index(fields=['production_line', 'date'], name='labor_labor_product_46b9c7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('project__isnull', False), ('task__isnull', False), ('production_line__isnull', False), _connector='OR'), name='labor_allocation_has_target'), models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('employee', 'date', 'project'), name='unique_allocation_per_employee_date_project'), models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('employee', 'date', 'task'), name='unique_allocation_per_employee_date_task'), models.UniqueConstraint(condition=models.Q(('production_line__isnull', False)), fields=('employee', 'date', 'production_line'), name='unique_allocation_per_employee_date_production_line')],
            },
        ),
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('SOFTWARE', 'Software'), ('MANAGEMENT', 'Management'), ('ADMINISTRATION', 'Administration'), ('QUALITY_CONTROL', 'Quality Control'), ('SAFETY', 'Safety'), ('LOGISTICS', 'Logistics'), ('MAINTENANCE', 'Maintenance'), ('OPERATIONS', 'Operations'), ('DESIGN', 'Design'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'skill matrix',
                'verbose_name_plural': 'skill matrices',
                'unique_together': {('employee', 'name')},
            },
        ),
    ]
