# Generated by Django 5.2.7 on 2025-10-11 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborallocation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='laborallocation',
            name='hours_allocated',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='laborallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skillmatrix',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillmatrix',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
