# Generated by Django 5.2.7 on 2025-10-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_processes', to='production.manufacturingprocess', verbose_name='process'),
        ),
        migrations.AddField(
            model_name='productprocess',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_processes', to='product.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_processes',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductProcess', to='production.manufacturingprocess', verbose_name='manufacturing processes'),
        ),
        migrations.AddIndex(
            model_name='productprocess',
            index=models.Index(fields=['product', 'process'], name='product_pro_product_adaa88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productprocess',
            unique_together={('product', 'process', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_pro_name_b60cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_pro_code_f66008_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='product_pro_status_48d769_idx'),
        ),
    ]
