name: ansible

services:
  control:
    build: ./control # uses the Dockerfile above
    container_name: ansible-control
    stdin_open: true # keep if you need interactive exec
    tty: true
    volumes:
      - .:/ansible
    working_dir: /ansible
    networks:
      - ansible-net
    depends_on:
      managed:
        condition: service_healthy

  managed:
    build: ./managed
    container_name: ansible-managed
    stdin_open: true
    tty: true
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD-SHELL", "ss -tlnp | grep -q :22"]
      interval: 2s
      timeout: 2s
      retries: 10

networks:
  ansible-net:
    driver: bridge
