# Generated by Django 5.2.7 on 2025-12-25 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_material_inventory_m_name_1014de_idx'),
        ('production', '0002_alter_productionline_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity consumed')),
                ('consumed_at', models.DateTimeField(auto_now_add=True, verbose_name='consumed at')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_material_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='consumed by')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_consumptions', to='inventory.material', verbose_name='material')),
                ('production_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_consumptions', to='production.productionschedule', verbose_name='production schedule')),
            ],
            options={
                'verbose_name': 'Production Material Consumption',
                'verbose_name_plural': 'Production Material Consumptions',
                'ordering': ['-consumed_at'],
                'indexes': [models.Index(fields=['production_schedule', 'material'], name='production__product_501e9a_idx'), models.Index(fields=['consumed_at'], name='production__consume_5e09a8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='production_consumption_quantity_positive')],
            },
        ),
    ]
