# Generated by Django 5.2.7 on 2026-02-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionmaterialconsumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionMaterialConsumption',
        ),
    ]
