# Generated by Django 5.2.7 on 2025-10-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machineoperatorassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='core.machine'),
        ),
        migrations.AddField(
            model_name='machineoperatorassignment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshop',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='core.department'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workshops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machine',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.workshop'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='core_depart_name_80d4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['supervisor'], name='core_depart_supervi_6347ad_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoperatorassignment',
            index=models.Index(fields=['assigned_at'], name='core_machin_assigne_c3d921_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoperatorassignment',
            index=models.Index(fields=['auto_remove_at'], name='core_machin_auto_re_dc1317_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoperatorassignment',
            index=models.Index(fields=['machine', 'status'], name='core_machin_machine_5f1261_idx'),
        ),
        migrations.AddIndex(
            model_name='machineoperatorassignment',
            index=models.Index(fields=['operator', 'status'], name='core_machin_operato_2123ef_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['name'], name='core_worksh_name_bb750e_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['manager'], name='core_worksh_manager_8f326b_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['department'], name='core_worksh_departm_ea7cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['operational_status'], name='core_worksh_operati_65f6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['name'], name='core_machin_name_b8bb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status'], name='core_machin_status_9645c0_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['workshop'], name='core_machin_worksho_a00bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['operator'], name='core_machin_operato_915038_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['operator_auto_remove_at'], name='core_machin_operato_239034_idx'),
        ),
    ]
